### PR TITLE
Dialogue placement

### PR DESCRIPTION
**Pull request by BeanDevStudios**
Pulled Items from @motzca  and @L0ST201. No issues. Placement of dialogue has been completed.

### CODE REVIEW

**Comment by motzca** [comment]
@BeanDevStudios There seems to be some issue with how the the variables are working. As an example when unpacking the rest of your items, it should be -15 to energy, but it only goes down by -5, making it 55. Then, suddenly, the energy goes to 25 on the next card and then -5 on the next. This is something that needs to be fixed. Also, you didn't fix your conflicting files.

**Comment by BeanDevStudios** [comment]
There are three different versions of Day 2.
Day 1 is unable to go to Day 2 because the blocks are looking for "Day 2" and not "Day 2A", "Day 2B", or "Day 2C". There will need to be an IF statement that says which day is selected.

**Comment by motzca** [comment]
> There are three different versions of Day 2. Day 1 is unable to go to Day 2 because the blocks are looking for "Day 2" and not "Day 2A", "Day 2B", or "Day 2C". There will need to be an IF statement that says which day is selected.

Can we not just have it go to the correct day it needs to go to??? Like having the Hops Route going to 2B??

**Comment by motzca** [comment]
@BeanDevStudios When looking at the block, each are assigned correctly. I'm not sure what you mean by this? Also, the same issues that I commented above are still occurring.

**Comment by BeanDevStudios** [comment]
> > There are three different versions of Day 2. Day 1 is unable to go to Day 2 because the blocks are looking for "Day 2" and not "Day 2A", "Day 2B", or "Day 2C". There will need to be an IF statement that says which day is selected.
> 
> 
> 
> Can we not just have it go to the correct day it needs to go to??? Like having the Hops Route going to 2B??

Yeah that's a simple thing. Just need to know which version connects with which day. I'll message you.

**Comment by motzca** [comment]
This seems to be working now. Let @L0ST201 also review it and then it can be merged.

**Review by motzca — APPROVED** [review]

**Review by motzca — APPROVED** [review]

**Pull request merged**
